import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex ">
      <ul className="w-[200px] bg-black text-white text-[20px]">
        <li>
          <Link href="/demo/child1">child1</Link>
        </li>
        <li>
          <Link href="/demo/child2">chlid2</Link>
        </li>
      </ul>
      <div className="flex-1 bg-slate-400 rounded-sm">{children}</div>
    </div>
  );
}
